on:
  issues:
    types:
      - edited
      - deleted
      - closed
      - reopened
  push:
    branched:
      - "master"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pip install markdown Pillow && python generate.py
