on:
  issues:

jobs:
  handle_issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: python handle_issue.py
